<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="mobile_robot">

  <xacro:include filename="$(find quimera_robot_description)/urdf/common_macro.xacro" />

  <xacro:property name="back_wheel_yaml" value="$(find quimera_robot_description)/config/back_wheel.yaml" />
  <xacro:property name="wheel_props" value="${load_yaml(back_wheel_yaml)}"/>

  <xacro:property name="front_wheel_yaml" value="$(find quimera_robot_description)/config/front_wheel.yaml" />
  <xacro:property name="front_wheel_props" value="${load_yaml(front_wheel_yaml)}"/>

  <xacro:property name="base_yaml" value="$(find quimera_robot_description)/config/base.yaml" />
  <xacro:property name="base_props" value="${load_yaml(base_yaml)}"/>

  <xacro:property name="PI" value="3.14"/>
  
  <!-- ####### Back Wheel Parameters ########## -->
  <!-- Offset distance from the outter border to the center of the wheel-->
  <xacro:property name="b_wheel_x_offset" value="0.128"/>
  <!-- Offset distance from the outter border to the face of the wheel -->
  <xacro:property name="b_wheel_y_offset" value="0.02"/>
  <!-- Offset distance from the bottom border to the center of the wheel -->
  <xacro:property name="b_wheel_z_offset" value="0.05"/>

  <!-- Back Wheel joint position -->
  <xacro:property name="b_wheel_pos_x_joint"
     value="${(base_props['base']['x_size']/2) - b_wheel_x_offset}"/>
  <xacro:property name="b_wheel_pos_y_joint"
    value="${(base_props['base']['y_size']/2) - b_wheel_y_offset - (wheel_props['wheel']['length']/2)}"/>
  <xacro:property name="b_wheel_pos_z_joint" value="${b_wheel_z_offset}"/>
  <!-- ######################################## -->

  <!-- ####### Front Wheel Parameters ########## -->
  <!-- Offset distance from the outter border to the center of the wheel-->
  <xacro:property name="f_wheel_x_offset" value="0.035"/>
  <!-- Offset distance from the outter border to the face of the wheel -->
  <xacro:property name="f_wheel_y_offset" value="0.050"/>
  <!-- Offset distance from the bottom border to the center of the wheel -->
  <xacro:property name="f_wheel_z_offset" value="0.008"/>

  <!-- Front Wheel joint position -->
  <xacro:property name="f_wheel_pos_x_joint" value="${(base_props['base']['x_size']/2) - f_wheel_x_offset}"/>
  <xacro:property name="f_wheel_pos_y_joint"
    value="${(base_props['base']['y_size']/2) - f_wheel_y_offset - (front_wheel_props['wheel']['length']/2)}"/>
  <xacro:property name="f_wheel_pos_z_joint" value="${f_wheel_z_offset}"/>
  <!-- ######################################## -->

  <!-- <xacro:macro name="get_parameters" params="yaml_name prefix">
    <xacro:property name="yaml" value="$(find quimera_robot_description)/config/${yaml_name}.yaml" />
    <xacro:property name="${prefix}_props" value="${load_yaml(yaml)}" scope="global"/>
  </xacro:macro> -->

  <!-- <xacro:get_parameters yaml_name="back_wheel" prefix="front"/> -->
  <!-- <xacro:property name="test_props" value="${props}"/> -->

  <!-- <xacro:get_parameters yaml_name="front_wheel"/>
  <xacro:property name="front_props" value="${props}"/> -->

  <!-- Base link -->
  <xacro:base base_prop="${base_props}" mesh="${base_props['base']['mesh']}" >
    <origin xyz="0 0 0" rpy="${PI/2} 0 -${PI/2}" />
  </xacro:base> 


  
  <!-- Back Wheel -->
  <xacro:wheel prefix="back_right" reflect="-1"
                      wheel_prop="${wheel_props}"
                      pos_x_joint="${b_wheel_pos_x_joint}"
                      pos_y_joint="${b_wheel_pos_y_joint}"
                      pos_z_joint="${b_wheel_pos_z_joint}"
                      mesh="${wheel_props['wheel']['mesh']}">
  </xacro:wheel>

  <xacro:wheel prefix="back_left" reflect="1"
                      wheel_prop="${wheel_props}"
                      pos_x_joint="${b_wheel_pos_x_joint}"
                      pos_y_joint="${b_wheel_pos_y_joint}"
                      pos_z_joint="${b_wheel_pos_z_joint}"
                      mesh="${wheel_props['wheel']['mesh']}">
  </xacro:wheel>

  <!-- Front Wheel -->
  <xacro:wheel prefix="front_right" reflect="-1" 
                      wheel_prop="${front_wheel_props}" 
                      pos_x_joint="${f_wheel_pos_x_joint}" 
                      pos_y_joint="${f_wheel_pos_y_joint}" 
                      pos_z_joint="${f_wheel_pos_z_joint}">
  </xacro:wheel>

  <xacro:wheel prefix="front_left" reflect="1" 
                      wheel_prop="${front_wheel_props}" 
                      pos_x_joint="${f_wheel_pos_x_joint}" 
                      pos_y_joint="${f_wheel_pos_y_joint}" 
                      pos_z_joint="${f_wheel_pos_z_joint}"> 
  </xacro:wheel>                      

  <!-- <xacro:include filename="$(find mobile_description)/urdf/mobile_robot_gazebo_plugins.xacro"/>  -->

</robot>