base:
  mass: 2.5               # Base mass in Kg
  x_size: 0.195           # Dimention in x axis
  y_size: 0.198           # Dimention in y axis
  z_size: 0.182           # Dimention in z axis
  mesh: 'quimera_struct'  # Name of the mesh files. Leave it empty ('') to have a white base.